##
# BUILD
##
FROM maven:3.6.3-openjdk-17 AS build
ARG BUCKET_NAME
ARG RDS_INSTANCE_ID
ARG RDS_INSTANCE_HOSTNAME
ARG RDS_DB_USER
ARG RDS_PASSWORD
ARG RDS_DATABASE
ARG RDS_INSTANCE_PORT
ARG RDS_REGION_NAME
ENV BUCKET_NAME=${BUCKET_NAME}
ENV RDS_INSTANCE_ID=${RDS_INSTANCE_ID}
ENV RDS_INSTANCE_HOSTNAME=${RDS_INSTANCE_HOSTNAME}
ENV RDS_DB_USER=${RDS_DB_USER}
ENV RDS_PASSWORD=${RDS_PASSWORD}
ENV RDS_DATABASE=${RDS_DATABASE}
ENV RDS_INSTANCE_PORT=${RDS_INSTANCE_PORT}
ENV RDS_REGION_NAME=${RDS_REGION_NAME}

COPY . .
RUN mvn clean package
##
# RUN
##
FROM openjdk:17
COPY --from=build /home/target/app-0.0.1-SNAPSHOT.jar app.jar
EXPOSE 8080
ENTRYPOINT [ "java","jar","app.jar" ]